################################
# MySQL \uC124\uC815 (\uAC1C\uBC1C\uC6A9 : Local 3306)
################################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################################
# JPA \uC124\uC815 (\uAC1C\uBC1C\uC6A9 : DDL \uB85C\uCEEC\uC5D0\uC11C \uAC1C\uC778 \uAD00\uB9AC)
################################
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

################################
# JPA / Hibernate \uB85C\uADF8 \uC124\uC815 (\uD544\uC694\uC2DC true\uB85C \uC124\uC815)
################################
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=WARN

################################
# \uCC38\uACE0 : DDL \uC790\uB3D9 \uC5C6\uB370\uC774\uD2B8 (\uCD08\uAE30 DB \uC0DD\uC131\uC6A9)
################################
# spring.jpa.hibernate.ddl-auto=update

################################
# swagger / api-docs (\uAC1C\uBC1C\uC6A9 : \uD65C\uC131\uD654)
################################
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true