################################
# swagger / api-docs (\uC6B4\uC601\uC6A9 : \uBE44\uD65C\uC131\uD654)
################################
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false