################################
# \uAE30\uBCF8 \uC124\uC815
################################
spring.application.name=TripMoa
server.port=8080

################################
# \uAC1C\uBC1C \uC11C\uBC84 \uC124\uC815
################################
cors.allowed-origins=http://localhost:3000,http://localhost:5173
oauth2.redirect-url=http://localhost:5173

################################
# \uC2E4\uD589 \uD504\uB85C\uD30C\uC77C
################################
spring.profiles.active=dev,oauth,secret

################################
# Security \uB85C\uADF8 \uC124\uC815
################################
logging.level.org.springframework.security=DEBUG

################################
# \uD30C\uC77C \uC5C5\uB85C\uB4DC \uC124\uC815
################################
file.upload-dir=./uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

################################
# Redis \uC124\uC815
################################
spring.data.redis.host=localhost
spring.data.redis.port=6379

################################
# \uC694\uCCAD/\uC751\uB2F5 \uBCF8\uBB38 \uBC84\uD37C \uD06C\uAE30 \uC81C\uD55C
################################
server.tomcat.max-http-form-post-size=10MB
spring.codec.max-in-memory-size=10MB
